export type ServiceDetail = {
  features: string[];
  technologies: string[];
  processSteps: { title: string; description: string }[];
  relatedSlugs: string[];
  contentParagraphs: string[];
};

const sharedProcess = [
  { title: "Discovery", description: "We align on goals, users, constraints, and measurable outcomes before writing code." },
  { title: "Architecture", description: "Technical design, stack selection, and delivery roadmap are documented and reviewed with your team." },
  { title: "Build", description: "Iterative development with demos, code reviews, and quality gates at every sprint." },
  { title: "Launch", description: "Deployment, monitoring, handover documentation, and support transition planning." },
];

export const serviceDetails: Record<string, ServiceDetail> = {
  "web-development": {
    features: [
      "Responsive, performance-optimised interfaces for all device sizes",
      "Scalable front-end architecture with component-driven design",
      "Secure authentication, authorisation, and session management",
      "SEO-friendly structure and metadata for discoverability",
      "Integration with CRMs, ERPs, payment gateways, and analytics",
      "Continuous delivery pipelines for reliable releases",
    ],
    technologies: ["Next.js", "React", "TypeScript", "Node.js", "PostgreSQL", "AWS", "Docker"],
    processSteps: sharedProcess,
    relatedSlugs: ["custom-software-development", "progressive-web-apps", "api-development"],
    contentParagraphs: [
      "Modern businesses depend on web applications that are fast, secure, and easy to evolve. At ITX Networks, web development is not limited to building pages—it is about engineering digital products that support real operational workflows, integrate with existing systems, and scale as your user base grows. We work with product owners, IT leaders, and founders across India to translate business requirements into reliable web platforms.",
      "Our approach begins with understanding how users interact with your product, what performance expectations exist, and which integrations are critical on day one versus later phases. We design information architecture, define component libraries, and establish coding standards that keep delivery predictable. Whether you need a customer portal, internal dashboard, SaaS platform, or public marketing site with dynamic functionality, we tailor the stack to your constraints rather than forcing a one-size-fits-all template.",
      "We specialise in React and Next.js ecosystems for teams that value maintainability and strong developer experience. Server-side rendering, static generation, and hybrid patterns are selected based on SEO needs, personalisation requirements, and infrastructure costs. Backend services are structured for clarity—REST or GraphQL APIs, background jobs, caching layers, and observability hooks are planned early so production issues are diagnosable, not mysterious.",
      "Security is embedded throughout the lifecycle. We implement role-based access control, input validation, secure headers, and environment separation for staging and production. For Indian enterprises handling sensitive data, we align with your compliance expectations and document data flows clearly. Performance optimisation includes bundle analysis, image strategies, database query tuning, and CDN configuration where appropriate.",
      "Our delivery model emphasises transparency. You receive regular demos, sprint reports, and a visible backlog so priorities can shift without losing control of scope. We also prepare maintainable documentation and knowledge transfer so your internal team can confidently extend the product after launch. When needed, we continue with SLA-backed maintenance and enhancement programmes.",
      "If you are replatforming from legacy PHP or monolithic systems, we plan phased migrations that reduce risk—parallel runs, feature flags, and incremental cutovers rather than big-bang releases. The result is a web application that feels modern to users while respecting the stability your business requires.",
    ],
  },
  "mobile-app-development": {
    features: [
      "Native and cross-platform strategies matched to your timeline and budget",
      "Offline-first patterns for field and low-connectivity scenarios",
      "Push notifications, deep linking, and in-app analytics integration",
      "App store submission support and release train management",
      "Secure local storage and biometric authentication options",
      "Performance profiling for smooth scrolling and battery efficiency",
    ],
    technologies: ["React Native", "Flutter", "Swift", "Kotlin", "Firebase", "GraphQL", "Fastlane"],
    processSteps: sharedProcess,
    relatedSlugs: ["cross-platform-development", "progressive-web-apps", "ui-ux-design"],
    contentParagraphs: [
      "Mobile applications are often the primary touchpoint between your business and users. ITX Networks builds mobile experiences that prioritise reliability, intuitive navigation, and maintainable codebases. From consumer-facing apps to enterprise field tools, we help Indian organisations ship products that perform consistently across devices and network conditions.",
      "We evaluate native versus cross-platform options with honesty—considering team skills, feature complexity, performance needs, and long-term maintenance costs. React Native and Flutter are strong choices for shared logic across iOS and Android, while native Swift or Kotlin may be preferable for hardware-intensive or platform-specific capabilities.",
      "Our mobile practice covers the full lifecycle: user flows, wireframes, API contracts, state management, automated testing, and store compliance. We design for accessibility, localisation readiness, and graceful degradation when services are unavailable. Offline sync, background tasks, and secure credential storage are implemented using established patterns rather than experimental shortcuts.",
      "Enterprise mobile projects frequently require integration with identity providers, document capture, GPS tracking, barcode scanning, or ERP backends. We map these integrations early, prototype risky areas, and build monitoring so field issues surface quickly. Release management includes staged rollouts, crash reporting, and version compatibility planning.",
      "Quality assurance combines device lab testing, automated UI tests, and beta programmes with real users. We track crash-free sessions, startup time, and API error rates as launch criteria. Post-launch, we support enhancement backlogs, OS upgrade validation, and store policy changes that affect existing apps.",
      "Whether you are launching a new product or rescuing an underperforming app, our team focuses on outcomes: faster task completion, higher engagement, and lower support burden. Mobile success is measured in daily usage, not just install counts.",
    ],
  },
  "windows-application-development": {
    features: [
      "WinForms, WPF, and WinUI modernisation paths",
      "Installer packaging and enterprise deployment support",
      "Integration with Active Directory and Windows services",
      "High-performance data processing on desktop hardware",
      "Legacy VB and .NET migration strategies",
      "Offline-capable desktop workflows for regulated environments",
    ],
    technologies: [".NET", "C#", "WPF", "WinUI 3", "SQL Server", "MSI", "Azure AD"],
    processSteps: sharedProcess,
    relatedSlugs: ["desktop-applications", "enterprise-applications", "software-modernization"],
    contentParagraphs: [
      "Windows remains essential for many Indian enterprises running manufacturing, finance, healthcare, and internal operations software. ITX Networks develops Windows applications that integrate cleanly with existing IT environments, support controlled deployment, and remain maintainable across years of enhancements.",
      "We build desktop software using .NET frameworks suited to your context—WPF and WinUI for rich interfaces, Windows Services for background processing, and modular architectures that separate UI from business logic. Applications are designed for role-based access, audit logging, and configurable workflows that match how teams actually work on the shop floor or back office.",
      "Deployment considerations are addressed early: MSI packaging, auto-update strategies, group policy compatibility, and offline operation when network access is intermittent. For organisations migrating from legacy VB or older WinForms codebases, we propose phased refactors that preserve critical functionality while improving testability and security.",
      "Integration with printers, scanners, serial devices, and line-of-business systems is common in Windows projects. We prototype hardware interactions, document failure modes, and implement diagnostics that help support teams resolve issues quickly. Performance tuning for large datasets, reporting, and batch imports is standard in our delivery checklist.",
      "Security practices include code signing, least-privilege execution, encrypted configuration, and secure communication with central APIs or databases. When cloud connectivity is required, we design resilient sync patterns that handle conflicts and temporary outages without data loss.",
      "Our Windows development engagements include thorough handover materials, administrator guides, and optional maintenance plans for OS compatibility updates and feature roadmaps.",
    ],
  },
  "custom-software-development": {
    features: [
      "Bespoke workflows aligned to your business rules",
      "Modular architecture for phased feature expansion",
      "Multi-tenant or single-tenant deployment options",
      "Comprehensive audit trails and reporting modules",
      "API-first design for future integrations",
      "Documentation and training for internal administrators",
    ],
    technologies: ["Java", "Python", ".NET", "Node.js", "PostgreSQL", "Kubernetes", "Redis"],
    processSteps: sharedProcess,
    relatedSlugs: ["enterprise-applications", "api-development", "software-consulting"],
    contentParagraphs: [
      "Off-the-shelf software rarely fits unique operational models. Custom software development at ITX Networks focuses on solving specific business problems with solutions you control—your workflows, your data model, your roadmap. We partner with Indian enterprises and growth companies that need software shaped around how they compete, not the other way around.",
      "Discovery is the foundation. We map current processes, pain points, integration points, and regulatory constraints before proposing architecture. Prototypes and clickable flows validate assumptions with stakeholders early, reducing rework during implementation. Our teams translate approved designs into incremental releases that deliver value before the entire vision is complete.",
      "Technical choices are pragmatic. We select languages and frameworks based on team familiarity, hiring markets, performance needs, and integration requirements. Microservices, modular monoliths, or well-structured single applications are all valid depending on scale and operational maturity. Data modelling receives dedicated attention because poor schema decisions become expensive later.",
      "Custom projects often touch multiple departments. We facilitate workshops, maintain decision logs, and manage scope transparently so prioritisation remains a business choice, not a surprise at invoice time. Automated testing, CI/CD, and staging environments give confidence that each release is production-ready.",
      "We also plan for ownership transition. Code repositories, deployment runbooks, and architecture diagrams are delivered so your internal team or alternate vendors can continue confidently. Optional support retainers cover enhancements, security patches, and infrastructure maintenance.",
      "When custom software succeeds, it becomes a competitive asset—not a workaround. That is the standard we hold every engagement to.",
    ],
  },
  "progressive-web-apps": {
    features: [
      "Installable experiences without app store friction",
      "Service worker strategies for offline and caching",
      "Push notification setup where supported",
      "App-like navigation and performance on mobile browsers",
      "Secure HTTPS and modern browser API usage",
      "Analytics and conversion tracking integration",
    ],
    technologies: ["Next.js", "Workbox", "React", "IndexedDB", "Web Push", "Lighthouse"],
    processSteps: sharedProcess,
    relatedSlugs: ["web-development", "mobile-app-development", "cross-platform-development"],
    contentParagraphs: [
      "Progressive Web Apps combine the reach of the web with capabilities users associate with native applications. ITX Networks helps organisations deploy PWAs when fast time-to-market, lower distribution cost, and cross-platform consistency matter more than deep hardware access.",
      "We assess PWA fit honestly. For many B2B portals, customer self-service hubs, and internal tools, a well-engineered PWA delivers excellent results. We define offline requirements, caching policies, and background sync behaviour that match real usage rather than demo scenarios.",
      "Implementation covers manifest configuration, service worker lifecycle management, asset precaching, and graceful fallbacks when advanced APIs are unavailable. Performance budgets and Core Web Vitals targets are tracked throughout development because PWA success depends on perceived speed.",
      "Security remains paramount—TLS everywhere, strict content policies, token refresh flows, and protection against common web vulnerabilities. We test across major mobile and desktop browsers used in your market, including variations common in enterprise environments.",
      "PWAs integrate with existing backends through REST or GraphQL APIs, reusing authentication infrastructure where possible. When requirements evolve toward native features, our modular front-end architecture simplifies partial migration paths.",
      "Launch includes monitoring real-user metrics, iteration on install prompts, and refinement of offline UX. PWAs should feel dependable on unreliable networks—that is where thoughtful engineering pays off.",
    ],
  },
  "cross-platform-development": {
    features: [
      "Single codebase targeting iOS, Android, and web where feasible",
      "Shared business logic with platform-specific UI polish",
      "Consistent release cadence across app stores",
      "Unified analytics and crash reporting",
      "Code reuse without sacrificing native feel",
      "Automated build pipelines for multi-platform artefacts",
    ],
    technologies: ["React Native", "Flutter", "Expo", "TypeScript", "Firebase", "Codemagic"],
    processSteps: sharedProcess,
    relatedSlugs: ["mobile-app-development", "progressive-web-apps", "ui-ux-design"],
    contentParagraphs: [
      "Cross-platform development reduces duplication while accelerating delivery—when architecture and team practices are disciplined. ITX Networks builds cross-platform applications that share core logic yet respect platform conventions users expect on iOS and Android.",
      "Framework selection depends on UI complexity, performance sensitivity, existing team skills, and third-party SDK requirements. We document trade-offs clearly so stakeholders understand why React Native, Flutter, or a hybrid approach is recommended.",
      "Shared modules handle authentication, networking, state management, and analytics, while platform channels address camera, biometrics, payments, and push notifications. Navigation patterns, typography, and spacing follow platform guidelines to avoid generic-looking interfaces.",
      "Testing strategy spans simulators, physical devices, and automated suites covering critical flows. Store compliance, privacy labels, and permission explanations are prepared early to prevent release delays.",
      "We plan upgrade paths for framework and OS versions, reducing technical debt that often accumulates in cross-platform codebases. Performance profiling identifies jank, memory leaks, and oversized bundles before users encounter them.",
      "Cross-platform is a business decision as much as a technical one. We align delivery milestones with marketing launches and operational readiness so all platforms go live cohesively.",
    ],
  },
  "enterprise-applications": {
    features: [
      "Role-based access with fine-grained permissions",
      "High availability and disaster recovery planning",
      "Enterprise SSO and directory integration",
      "Workflow automation and approval chains",
      "Operational dashboards and exportable reports",
      "Compliance-ready logging and data retention policies",
    ],
    technologies: ["Java", "Spring Boot", ".NET", "Oracle", "PostgreSQL", "Kafka", "Kubernetes"],
    processSteps: sharedProcess,
    relatedSlugs: ["custom-software-development", "database-development", "cloud-applications"],
    contentParagraphs: [
      "Enterprise applications power core operations—ERP extensions, compliance systems, partner portals, and internal platforms that cannot afford downtime or ambiguous security. ITX Networks delivers enterprise-grade software with the rigour Indian and global organisations expect from long-term technology partners.",
      "We begin with non-functional requirements: availability targets, concurrent user loads, data residency, audit needs, and integration with identity providers. Architecture reviews involve your IT stakeholders so deployment models align with internal standards.",
      "Development emphasises modular services, clear domain boundaries, and automated testing at multiple levels. Batch processing, event-driven workflows, and reporting pipelines are designed for observability—metrics, structured logs, and traceable transactions.",
      "Enterprise rollouts require change management. We support pilot groups, training materials, phased feature activation, and hypercare periods after go-live. Data migration scripts are tested repeatedly against anonymised production samples when possible.",
      "Security controls include encryption at rest and in transit, secrets management, vulnerability scanning, and regular dependency updates. We collaborate with your security team on penetration test remediation and access reviews.",
      "Long-term success means predictable evolution. We document extension points and offer maintenance programmes that keep enterprise systems current without disruptive rewrites.",
    ],
  },
  "desktop-applications": {
    features: [
      "Cross-platform desktop using Electron or native stacks",
      "Local data processing with optional cloud sync",
      "Auto-update mechanisms and version compatibility",
      "Hardware and peripheral integration where required",
      "Offline-first workflows for remote teams",
      "Installer creation for Windows, macOS, and Linux",
    ],
    technologies: ["Electron", ".NET", "Qt", "SQLite", "Node.js", "macOS Notarization"],
    processSteps: sharedProcess,
    relatedSlugs: ["windows-application-development", "custom-software-development", "software-modernization"],
    contentParagraphs: [
      "Desktop applications remain vital for power users, creative tools, data-heavy workflows, and environments where browser-based solutions are insufficient. ITX Networks builds desktop software that feels responsive, installs cleanly, and integrates with OS-level capabilities.",
      "Platform coverage is planned upfront—Windows-only, macOS support, or Linux variants for specialised deployments. We choose Electron, .NET, Qt, or native stacks based on performance, packaging requirements, and team maintainability.",
      "Local databases, file system access, and background processing are implemented with clear error handling and recovery paths. When cloud sync is needed, conflict resolution and bandwidth-aware sync protect user data during connectivity issues.",
      "Update strategies range from silent auto-updates to IT-controlled rollouts in locked-down enterprises. Code signing, notarisation, and antivirus false-positive mitigation are part of our release checklist.",
      "Usability matters on desktop as much as mobile. Keyboard shortcuts, multi-window layouts, drag-and-drop, and accessible contrast ratios are considered throughout design. Performance profiling ensures large files and datasets remain manageable.",
      "We deliver installers, uninstallers, configuration guides, and optional telemetry dashboards so product owners understand adoption and crash trends after launch.",
    ],
  },
  "software-modernization": {
    features: [
      "Legacy codebase assessment and risk mapping",
      "Strangler fig migration and incremental cutover",
      "Cloud rehosting and containerisation paths",
      "Database refactoring and performance remediation",
      "UI modernisation without losing business logic",
      "Knowledge capture from legacy subject matter experts",
    ],
    technologies: ["Kubernetes", "Docker", "AWS", "Azure", "PostgreSQL", "API Gateway", "Terraform"],
    processSteps: sharedProcess,
    relatedSlugs: ["enterprise-applications", "cloud-applications", "maintenance-support"],
    contentParagraphs: [
      "Legacy systems accumulate risk—unsupported frameworks, shrinking talent pools, security gaps, and inability to integrate with modern SaaS tools. Software modernisation at ITX Networks is a structured programme to evolve critical systems without betting the business on a single big-bang rewrite.",
      "We start with an honest assessment: code quality, dependency health, infrastructure costs, failure patterns, and business-critical modules. Heat maps prioritise what to refactor, wrap with APIs, replace, or retire. Stakeholders receive a roadmap with phases, costs, and measurable benefits.",
      "Common patterns include extracting services from monoliths, introducing API layers for new channels, migrating databases with dual-write periods, and rebuilding front-ends while preserving validated business rules. Each phase delivers usable value and reduces rollback risk.",
      "Modernisation touches people as well as code. We document tribal knowledge, pair with internal teams, and run training so maintainership transitions smoothly. Automated tests are introduced around stable behaviour before structural changes accelerate.",
      "Cloud migration may accompany modernisation—containerisation, managed databases, and autoscaling for variable load. FinOps considerations help right-size resources so modern does not mean wasteful.",
      "The goal is a system your organisation can evolve for the next decade—not another legacy trap with newer logos.",
    ],
  },
  "maintenance-support": {
    features: [
      "SLA-backed incident response and escalation paths",
      "Proactive monitoring and health dashboards",
      "Security patch management and dependency updates",
      "Performance tuning and capacity planning",
      "Minor enhancements and backlog grooming",
      "Monthly service reports with trend analysis",
    ],
    technologies: ["Datadog", "Sentry", "GitHub Actions", "AWS CloudWatch", "PagerDuty", "Docker"],
    processSteps: sharedProcess,
    relatedSlugs: ["software-modernization", "software-testing", "cloud-applications"],
    contentParagraphs: [
      "Launch day is the beginning of a product's operational life. ITX Networks provides application maintenance and support that keeps systems secure, performant, and aligned with changing business needs. We serve clients across India who require dependable partners beyond initial development.",
      "Support engagements define severity levels, response times, communication channels, and maintenance windows acceptable to your operations. On-call rotations and escalation matrices ensure critical incidents receive immediate attention while lower-priority requests are triaged fairly.",
      "Proactive maintenance includes dependency audits, OS and runtime updates, certificate renewals, database maintenance, and backup verification. Monitoring alerts are tuned to reduce noise yet catch anomalies early—error rate spikes, latency degradation, disk exhaustion.",
      "Enhancement work is managed through a visible backlog with regular prioritisation sessions. Small improvements compound into major usability gains without requiring separate project contracts for every request.",
      "We produce service reports summarising incidents, root causes, preventive actions, uptime metrics, and upcoming risks. Transparency builds trust and helps leadership plan investments.",
      "Whether we built the original system or inherit it from another vendor, we invest time upfront to stabilise environments, document runbooks, and establish baseline metrics before aggressive changes.",
    ],
  },
  "ui-ux-design": {
    features: [
      "User research, personas, and journey mapping",
      "Wireframes, prototypes, and usability testing",
      "Design systems with reusable components",
      "Accessibility considerations (WCAG-oriented patterns)",
      "Developer-ready specs and asset handoff",
      "Conversion-focused landing and funnel design",
    ],
    technologies: ["Figma", "FigJam", "Maze", "Storybook", "Tailwind CSS", "Design Tokens"],
    processSteps: sharedProcess,
    relatedSlugs: ["web-development", "mobile-app-development", "custom-software-development"],
    contentParagraphs: [
      "Great software starts with clarity about user needs. ITX Networks UI/UX design services bridge business goals and engineering execution through research, structured design systems, and iterative validation.",
      "We conduct stakeholder interviews, workflow observations, and competitive reviews to understand where users struggle today. Personas and journey maps keep teams aligned on priorities—not assumptions. Low-fidelity wireframes explore layout and navigation before visual polish consumes budget.",
      "High-fidelity designs use consistent typography, spacing, colour tokens, and component states that map cleanly to front-end implementation. Interactive prototypes enable usability tests with real users, revealing friction before development sprints commit to paths.",
      "Accessibility is integrated from the start—contrast ratios, focus order, form labels, and error messaging that assistive technologies can interpret. Inclusive design expands reach and reduces retrofit costs.",
      "Handoff includes annotated specs, exportable assets, and collaboration with engineers during implementation to resolve edge cases. Design systems grow with products, preventing visual drift across modules and teams.",
      "For B2B and enterprise interfaces, we emphasise density, scanability, and efficient task completion over decorative trends. Good design measurably reduces training time, support tickets, and user errors.",
    ],
  },
  "database-development": {
    features: [
      "Conceptual and logical schema design",
      "Query optimisation and index strategy",
      "Migration scripts with rollback plans",
      "Replication, backup, and recovery architecture",
      "Data warehousing and reporting structures",
      "Performance benchmarking under realistic loads",
    ],
    technologies: ["PostgreSQL", "MySQL", "SQL Server", "Oracle", "MongoDB", "Redis", "Flyway"],
    processSteps: sharedProcess,
    relatedSlugs: ["enterprise-applications", "api-development", "cloud-applications"],
    contentParagraphs: [
      "Applications depend on data layers that remain correct under concurrency, scale gracefully, and recover reliably from failures. ITX Networks database design and development services ensure your data model supports current requirements and anticipated growth.",
      "We analyse entities, relationships, cardinality, and access patterns before finalising schemas. Normalisation and denormalisation decisions are documented with trade-offs explicit. Naming conventions and migration tooling keep environments synchronised across development, staging, and production.",
      "Performance work includes explain plan analysis, index tuning, partition strategies, and connection pool configuration. We load-test critical queries with datasets that reflect production volume—not empty tables.",
      "High availability setups leverage replication, automated failover, and backup schedules tested through restore drills. Point-in-time recovery and retention policies align with your compliance obligations.",
      "For analytics needs, we design staging areas, ETL pipelines, and reporting schemas that do not compromise transactional performance. Slowly changing dimensions, aggregations, and refresh schedules are planned with business consumers.",
      "Database engagements include operational runbooks so your team understands monitoring signals, maintenance tasks, and escalation paths when anomalies appear.",
    ],
  },
  "api-development": {
    features: [
      "REST and GraphQL API design with versioning",
      "OAuth2, JWT, and API key authentication patterns",
      "Rate limiting, throttling, and abuse protection",
      "OpenAPI documentation and developer portals",
      "Webhook design with retry and signature verification",
      "Third-party SaaS and legacy system connectors",
    ],
    technologies: ["Node.js", "FastAPI", "Spring Boot", "Kong", "Postman", "OpenAPI", "gRPC"],
    processSteps: sharedProcess,
    relatedSlugs: ["custom-software-development", "cloud-applications", "software-testing"],
    contentParagraphs: [
      "APIs are the connective tissue of modern software ecosystems. ITX Networks designs and builds APIs that are consistent, secure, well-documented, and resilient under production traffic.",
      "We begin with consumer analysis—mobile apps, partner integrations, internal microservices, or public developer platforms. Resource modelling, error conventions, pagination, and idempotency rules are standardised before implementation accelerates.",
      "Authentication and authorisation integrate with your identity provider or custom user stores. Secrets rotation, scope minimisation, and audit logging protect sensitive operations. Rate limits and payload validation defend against accidental overload and malicious abuse.",
      "Documentation is treated as a deliverable. OpenAPI specifications, example requests, sandbox environments, and changelog discipline help integrators succeed without constant support tickets.",
      "For legacy connectivity, we build adapter layers that shield modern consumers from outdated protocols or fragile upstream systems. Circuit breakers, retries with backoff, and dead-letter queues improve reliability.",
      "Monitoring tracks latency percentiles, error budgets, and saturation indicators. APIs are versioned thoughtfully so consumers upgrade on predictable schedules without breaking changes surprises.",
    ],
  },
  "software-testing": {
    features: [
      "Test strategy aligned to risk and release cadence",
      "Automated unit, integration, and E2E suites",
      "Performance and load testing for critical paths",
      "Regression packs integrated into CI pipelines",
      "Defect triage with reproducible steps and severity",
      "UAT support and release sign-off documentation",
    ],
    technologies: ["Playwright", "Cypress", "Jest", "k6", "Postman", "GitHub Actions", "TestRail"],
    processSteps: sharedProcess,
    relatedSlugs: ["maintenance-support", "custom-software-development", "api-development"],
    contentParagraphs: [
      "Quality is not a phase—it is a practice embedded throughout delivery. ITX Networks software testing and QA services help teams ship with confidence by combining manual exploration and automated regression.",
      "We develop test strategies mapped to business risk: payment flows, authentication, data integrity, and regulatory features receive deeper coverage than cosmetic variations. Test cases trace to requirements so gaps are visible before release.",
      "Automation frameworks are selected for maintainability. Flaky tests are treated as defects—they erode trust in CI. We structure page objects, fixtures, and data factories that scale with product complexity.",
      "Performance testing validates response times, throughput, and resource usage under expected and peak loads. Bottlenecks identified early are far cheaper to fix than production firefights.",
      "Defect management includes clear reproduction steps, environment details, severity classification, and verification cycles. Release readiness reports summarise open risks explicitly so stakeholders make informed go/no-go decisions.",
      "QA can augment your team continuously or engage for release hardening before major launches. Either way, the objective is fewer escaped defects and faster, calmer deployments.",
    ],
  },
  "cloud-applications": {
    features: [
      "Cloud-native architecture on AWS, Azure, or GCP",
      "Infrastructure as code and environment parity",
      "Autoscaling, load balancing, and CDN configuration",
      "Observability with metrics, logs, and traces",
      "Cost optimisation and FinOps reporting",
      "Disaster recovery and multi-region strategies",
    ],
    technologies: ["AWS", "Azure", "GCP", "Terraform", "Kubernetes", "Lambda", "CloudFront"],
    processSteps: sharedProcess,
    relatedSlugs: ["api-development", "enterprise-applications", "maintenance-support"],
    contentParagraphs: [
      "Cloud platforms enable elasticity, global reach, and managed services—but only when architecture avoids unnecessary complexity. ITX Networks builds cloud applications that leverage platform strengths while controlling cost and operational burden.",
      "We evaluate serverless, container, and managed service options against team skills and traffic patterns. Infrastructure as code ensures reproducible environments and auditable changes. Security groups, private networking, and secrets management are configured deliberately, not copied from tutorials.",
      "Applications are instrumented from day one—structured logging, distributed tracing, and dashboards that on-call engineers can act on. Autoscaling policies are tested with realistic load profiles, not assumed.",
      "Cost reviews identify idle resources, oversized instances, and storage lifecycle opportunities. FinOps is ongoing discipline, not a one-time exercise after bill shock.",
      "Disaster recovery plans define RPO/RTO targets, backup verification, and failover drills. Multi-region strategies are recommended only when business continuity requirements justify added complexity.",
      "Cloud engagements include documentation for deployment, rollback, and incident response so your team is not dependent on tribal knowledge when schedules change.",
    ],
  },
  "ecommerce-development": {
    features: [
      "B2C and B2B storefront configuration",
      "Catalogue, inventory, and order management flows",
      "Payment gateway and tax calculation integration",
      "Promotions, coupons, and loyalty mechanics",
      "Analytics, funnel tracking, and conversion optimisation",
      "ERP, logistics, and accounting system connectors",
    ],
    technologies: ["Shopify", "WooCommerce", "Magento", "Stripe", "Razorpay", "Node.js", "React"],
    processSteps: sharedProcess,
    relatedSlugs: ["web-development", "cms-development", "api-development"],
    contentParagraphs: [
      "E-commerce platforms must balance merchandising flexibility, checkout reliability, and operational efficiency. ITX Networks develops online commerce solutions for Indian businesses selling domestically and internationally.",
      "We implement B2C storefronts, B2B portals with contract pricing, and hybrid models where dealers and end customers coexist. Platform selection—custom build, Shopify, WooCommerce, or headless commerce—depends on catalogue complexity, integration needs, and internal marketing autonomy.",
      "Checkout flows minimise friction while supporting GST calculations, multiple payment methods, and fraud safeguards appropriate to your risk profile. Order management integrates with warehouse, courier, and accounting systems to reduce manual reconciliation.",
      "Performance and SEO directly affect revenue. We optimise category pages, faceted search, image delivery, and mobile experiences. Structured data and clean URL strategies improve discoverability.",
      "Merchandising teams receive admin tools and documentation for campaigns, collections, and inventory updates. Staging environments allow marketing to preview changes safely.",
      "Post-launch, we monitor conversion metrics, cart abandonment, and payment failures—iterating on UX and infrastructure before peak seasons arrive.",
    ],
  },
  "cms-development": {
    features: [
      "Custom CMS or headless content platforms",
      "Role-based publishing workflows and approvals",
      "Media library management and CDN delivery",
      "Multi-site and localisation support",
      "SEO metadata and structured content models",
      "Migration from legacy CMS platforms",
    ],
    technologies: ["Strapi", "Contentful", "WordPress", "Next.js", "Sanity", "AWS S3", "CloudFront"],
    processSteps: sharedProcess,
    relatedSlugs: ["web-development", "ecommerce-development", "ui-ux-design"],
    contentParagraphs: [
      "Content teams need systems that empower publishing without risking layout breakage or security incidents. ITX Networks CMS development services deliver flexible content models, approval workflows, and front-end experiences tuned to your brand.",
      "Headless CMS architectures decouple content from presentation— enabling web, mobile, and partner channels to consume the same structured content. We model content types, relationships, and validation rules that reflect editorial reality, not developer convenience alone.",
      "Workflow features include draft states, reviewer assignments, scheduled publishing, and audit history. Media handling covers image transformations, alt text requirements, and CDN-backed delivery for global performance.",
      "For marketing sites requiring frequent campaign updates, we integrate visual editors where appropriate while preserving component guardrails. Developers retain control of performance-critical layouts; marketers gain autonomy within safe boundaries.",
      "Migrations from legacy CMS platforms are planned with URL mapping, redirect rules, and content normalization scripts. SEO equity is protected through structured cutover steps.",
      "Training and editorial guides ensure teams adopt new tools confidently. CMS success is measured by publishing speed and reduced developer bottlenecks—not just feature checklists.",
    ],
  },
  "software-consulting": {
    features: [
      "Architecture reviews and technical due diligence",
      "Technology stack selection and roadmap planning",
      "Delivery process assessment and improvements",
      "Team structure and hiring guidance",
      "Security and scalability recommendations",
      "Vendor evaluation and build-vs-buy analysis",
    ],
    technologies: ["Architecture Diagrams", "C4 Model", "ADR", "Cloud Well-Architected", "Agile", "TOGAF-lite"],
    processSteps: sharedProcess,
    relatedSlugs: ["software-modernization", "enterprise-applications", "custom-software-development"],
    contentParagraphs: [
      "Not every engagement starts with code. ITX Networks software consulting helps leadership teams make informed decisions about architecture, vendors, timelines, and organisational capability before major investments commit.",
      "Consulting engagements often begin with discovery interviews and artifact reviews—existing documentation, codebase samples, infrastructure diagrams, and incident history. We identify risks, bottlenecks, and quick wins that improve outcomes regardless of build path.",
      "Architecture assessments evaluate scalability, security, maintainability, and alignment with business strategy. Recommendations are prioritised with effort estimates so budgets can be allocated realistically across quarters.",
      "Build versus buy analyses compare custom development, commercial platforms, and hybrid approaches with total cost of ownership in mind—not licence price alone. Integration complexity, vendor lock-in, and internal maintenance burden are weighed explicitly.",
      "We facilitate workshops with engineering and business stakeholders, producing decision records that survive personnel changes. Roadmaps connect technical initiatives to measurable business outcomes.",
      "Consulting can stand alone or transition seamlessly into implementation when you are ready. Our advice is practical because we ship software ourselves—we understand delivery constraints firsthand.",
    ],
  },
};

export function getServiceDetail(slug: string): ServiceDetail | undefined {
  return serviceDetails[slug];
}

export function getWordCount(detail: ServiceDetail): number {
  return detail.contentParagraphs.join(" ").split(/\s+/).filter(Boolean).length;
}
