export const serviceExpansions: Record<string, string[]> = {
  "web-development": [
    "For Indian enterprises, web platforms often need to support regional workflows, GST-related data capture, role hierarchies across branches, and integrations with accounting or logistics systems already in use. We map these requirements early so the application architecture accommodates them without costly rework later in the programme.",
    "Our delivery teams work closely with your stakeholders through structured sprint reviews, shared documentation, and environment access that mirrors production behaviour. This transparency helps business teams validate features while engineering teams maintain velocity and code quality throughout the build.",
    "Performance and reliability are validated using realistic test data, staging environments, and monitoring hooks before go-live. We also prepare rollback plans and deployment runbooks so your operations team can manage releases confidently after handover.",
    "Whether you need a greenfield product or a phased replatforming of an existing site, ITX Networks provides a practical roadmap aligned to budget, internal capacity, and business priorities across India and international markets.",
  ],
  "mobile-app-development": [
    "Mobile projects for Indian businesses frequently require offline capability, low-bandwidth tolerance, and interfaces that work well across a wide range of Android devices. We design and test with these constraints in mind rather than assuming always-on connectivity or flagship hardware.",
    "We support product owners with release planning, store listing preparation, and post-launch analytics review. Crash reporting, session monitoring, and user feedback loops are configured so improvements are driven by evidence rather than assumptions.",
    "Security considerations include secure token storage, certificate pinning where appropriate, and careful handling of personally identifiable information. We document data flows clearly for internal review and compliance discussions with your team.",
    "From MVP launches to enterprise field applications, our mobile practice focuses on maintainable codebases, predictable delivery, and long-term support options after initial release.",
  ],
  "windows-application-development": [
    "Many Indian organisations continue to depend on Windows desktops for specialised operational software. We build applications that respect existing IT policies, directory services, and deployment tooling while improving usability and maintainability.",
    "Our teams document installation steps, administrator configuration, and troubleshooting guidance so support staff can resolve common issues without developer intervention. This operational clarity is essential for software used daily across business units.",
    "When migrating from older desktop codebases, we identify modules that can be refactored incrementally versus those requiring replacement. This phased approach reduces business risk while still moving the overall system forward.",
    "ITX Networks delivers Windows software with a focus on stability, auditability, and integration with central databases or APIs used by your wider technology estate.",
  ],
  "custom-software-development": [
    "Custom software engagements begin with a shared understanding of the problem, the users affected, and the metrics that define success. We facilitate workshops, document decisions, and validate assumptions before significant development investment is committed.",
    "Our engineers favour clear domain modelling, automated testing, and modular architecture so future enhancements do not require rewriting the system. This is particularly important for organisations whose processes evolve seasonally or through regulatory change.",
    "We integrate with your existing tools—ERPs, CRMs, identity providers, reporting platforms—using well-defined interfaces that can be maintained by your internal team or future partners. Integration complexity is surfaced early with mitigation options.",
    "ITX Networks acts as a long-term technology partner, not merely a short-term vendor. Our goal is software that remains an asset as your organisation grows and adapts.",
  ],
  "progressive-web-apps": [
    "Progressive Web Apps are often the right choice when you need rapid distribution, lower platform fees, and consistent experiences across devices without maintaining separate native codebases for every channel.",
    "We define offline behaviour, caching policies, and update strategies that reflect how your users actually work—whether in offices, warehouses, retail floors, or customer-facing service environments across India.",
    "Accessibility, performance budgets, and search-friendly structure are treated as core requirements. PWAs should feel fast and dependable; we measure Core Web Vitals and iterate before launch.",
    "When your roadmap later requires native capabilities, our modular front-end architecture simplifies partial migration without discarding the investment already made in your web platform.",
  ],
  "cross-platform-development": [
    "Cross-platform development can significantly reduce time to market when architecture, testing, and platform conventions are handled with discipline. We help you choose the right framework based on feature needs, team skills, and release expectations.",
    "Shared business logic, unified analytics, and consistent release processes reduce operational overhead compared with maintaining entirely separate iOS and Android teams. We implement patterns that maximise reuse without producing generic user experiences.",
    "Store compliance, permission explanations, and OS upgrade validation are part of our release checklist. These details frequently cause delays when handled late; we address them throughout delivery.",
    "ITX Networks supports cross-platform products from initial build through enhancement cycles, performance tuning, and long-term maintenance programmes.",
  ],
  "enterprise-applications": [
    "Enterprise programmes require alignment between business stakeholders, IT governance, and delivery teams. We invest time upfront in non-functional requirements, integration mapping, and rollout planning so production deployment is controlled and auditable.",
    "Batch processing, workflow automation, and reporting pipelines are designed with observability in mind. Operations teams receive dashboards, alerts, and runbooks that support day-to-day management after go-live.",
    "Data migration, user training, and hypercare support are planned as explicit workstreams rather than afterthoughts. This reduces disruption when critical systems transition to new software.",
    "ITX Networks delivers enterprise applications with the rigour Indian and global organisations expect from a dependable software partner.",
  ],
  "desktop-applications": [
    "Desktop software remains essential for workflows involving large datasets, hardware peripherals, or power-user interfaces that web browsers cannot support efficiently. We evaluate platform coverage and deployment models before implementation begins.",
    "Auto-update strategies, code signing, and enterprise packaging are handled as first-class delivery tasks. Support teams receive clear guidance for installation, configuration, and common recovery scenarios.",
    "Performance profiling ensures responsive interaction even when processing substantial files or running long-running background tasks. Usability details such as keyboard shortcuts and accessible contrast are considered throughout design.",
    "Our desktop practice supports both new product development and modernisation of existing applications that your organisation relies on daily.",
  ],
  "software-modernization": [
    "Modernisation programmes succeed when priorities are evidence-based. We assess code health, infrastructure cost, incident history, and business criticality to recommend a phased roadmap with measurable outcomes at each stage.",
    "Strangler patterns, API extraction, database migration, and UI refresh can often proceed in parallel streams that deliver value without halting current operations. We document rollback paths and validation criteria for every phase.",
    "Knowledge transfer is built into modernisation work so your internal teams understand the target architecture and can participate in ongoing maintenance. Automated tests protect stable behaviour while structural improvements accelerate.",
    "ITX Networks helps organisations escape legacy traps by combining pragmatic engineering with transparent programme management.",
  ],
  "maintenance-support": [
    "Production systems require ongoing attention after launch—security updates, dependency changes, performance tuning, and user-driven enhancements. Our maintenance services are structured with clear severity levels and response expectations.",
    "Proactive monitoring, backup verification, and certificate management reduce preventable incidents. We tune alerts to surface meaningful anomalies without overwhelming on-call teams with noise.",
    "Enhancement requests are managed through a visible backlog with regular prioritisation sessions. Small improvements compound into significant usability and efficiency gains over time.",
    "Whether we built the original system or inherit it from another vendor, ITX Networks stabilises environments first, then improves them with measurable service reporting.",
  ],
  "ui-ux-design": [
    "Effective design starts with understanding user tasks, failure points, and operational constraints. We use interviews, workflow reviews, and prototype testing to validate direction before development sprints commit to final layouts.",
    "Design systems with reusable components help products scale without visual inconsistency. Developers receive specifications that reduce ambiguity during implementation and speed up delivery.",
    "Accessibility is integrated from the beginning—focus order, contrast, form labelling, and error messaging that assistive technologies can interpret correctly. Inclusive design expands reach and reduces retrofit cost.",
    "ITX Networks design services connect research, interface craft, and engineering feasibility for B2B and enterprise products used across India.",
  ],
  "database-development": [
    "Data layer decisions affect performance, integrity, and future flexibility. We model entities and access patterns carefully, document trade-offs between normalisation and denormalisation, and plan migrations with rollback safeguards.",
    "Query optimisation, indexing strategy, and load testing against realistic volumes are standard in our database engagements. Empty-table benchmarks are avoided because they mislead stakeholders about production behaviour.",
    "Backup, replication, and recovery procedures are tested through restore drills aligned to your recovery point and recovery time objectives. Operational runbooks support your team after handover.",
    "For analytics requirements, we design staging structures and refresh processes that protect transactional performance while enabling reporting consumers.",
  ],
  "api-development": [
    "Well-designed APIs reduce integration cost and support ecosystem growth. We standardise resource naming, error formats, pagination, authentication, and versioning so consumers can integrate confidently.",
    "Documentation, sandbox environments, and example requests are treated as deliverables equal in importance to the implementation itself. This reduces support burden and accelerates partner onboarding.",
    "For legacy connectivity, adapter layers shield modern consumers from fragile upstream systems. Retries, circuit breakers, and queue-based processing improve reliability under real-world conditions.",
    "ITX Networks builds APIs with security, observability, and long-term maintainability as core requirements from the first sprint.",
  ],
  "software-testing": [
    "Quality assurance should reflect business risk. Critical flows—authentication, payments, data integrity, regulatory features—receive deeper coverage than cosmetic variations that pose lower operational impact.",
    "Automation is implemented for maintainability. Flaky tests are corrected because they erode confidence in continuous integration. We structure suites so they scale with product complexity.",
    "Performance and regression testing are integrated into release readiness reviews with explicit go/no-go reporting. Defects are triaged with reproducible steps and clear severity classification.",
    "Our QA practice supports dedicated test phases, continuous engagement within agile teams, and hardening sprints before major launches.",
  ],
  "cloud-applications": [
    "Cloud adoption should reduce operational burden without introducing unnecessary complexity. We select serverless, container, or managed services based on traffic patterns, team skills, and cost constraints.",
    "Infrastructure as code, environment parity, and secrets management are implemented deliberately. Security groups, private networking, and access policies follow least-privilege principles.",
    "Applications are instrumented with metrics, logs, and traces that on-call engineers can act upon. Autoscaling policies are validated using realistic load rather than assumptions.",
    "ITX Networks helps organisations modernise infrastructure while controlling spend and maintaining operational clarity after deployment.",
  ],
  "ecommerce-development": [
    "E-commerce platforms must balance merchandising flexibility, checkout reliability, and back-office efficiency. We implement storefronts and admin tools suited to your catalogue complexity and operational model.",
    "GST calculations, payment methods, inventory synchronisation, and courier integrations are common requirements for Indian commerce projects. We plan these integrations early with clear ownership between systems.",
    "Performance and SEO directly influence revenue. Category pages, search, image delivery, and mobile checkout receive focused optimisation before peak trading periods.",
    "Post-launch, we monitor conversion metrics, payment failures, and operational bottlenecks to guide iterative improvements.",
  ],
  "cms-development": [
    "Content teams need systems that empower publishing without breaking layout or security boundaries. We model content types, workflows, and permissions that reflect editorial reality.",
    "Headless architectures allow web, mobile, and partner channels to consume structured content consistently. Media handling includes transformations, alt text requirements, and CDN-backed delivery.",
    "Migration from legacy CMS platforms includes URL mapping, redirect planning, and content normalisation scripts to protect search visibility during cutover.",
    "Training and editorial guides ensure teams adopt new tools confidently after launch.",
  ],
  "software-consulting": [
    "Consulting engagements help leadership teams make informed technology decisions before major spend is committed. We review architecture, delivery practices, vendor options, and organisational readiness with practical recommendations.",
    "Assessments identify quick wins alongside longer-term initiatives, enabling phased investment aligned to budget cycles. Decision records preserve rationale when teams or vendors change.",
    "Build versus buy analysis considers integration effort, maintenance burden, and total cost of ownership—not licence price alone. We present trade-offs clearly so stakeholders can choose deliberately.",
    "Consulting can transition into implementation when you are ready, with continuity from the same partner who understands your context.",
  ],
};
